{ stdenv, lib, asus-src }:

# libshared — ASUSWRT-Merlin shared utility library.
#
# This is the core library used by all Merlin components.
# Combines source-compiled objects with prebuilt Broadcom blobs.
# Build flags match Merlin's router/shared/Makefile for HND_ROUTER_AX.

let
  srcBase = "${asus-src}/release/src-rt-5.02axhnd";
  router = "${srcBase}/router";
  hndSrc = srcBase;
  kernelConfig = "${srcBase}/kernel/linux-4.1/config_base.6a";

  # Broadcom wireless SDK include paths (for typedefs.h, wlioctl.h, bcmendian.h)
  wlSrc = "${srcBase}/bcmdrivers/broadcom/net/wl/impl51/main/src/include";
  wlShared = "${srcBase}/bcmdrivers/broadcom/net/wl/impl51/main/src/shared";

  # cross-compiler tool prefix
  toolPrefix = stdenv.cc.targetPrefix;

  # Compiler flags matching Merlin's shared/Makefile for HND_ROUTER_AX
  # NOTE: kernel headers intentionally omitted — they conflict with modern
  # glibc (C23 keyword clash) and aren't needed for userspace code.
  baseCFlags = [
    "-Os" "-Wall" "-fPIC"
    "-I${router}/shared"
    "-I${router}"
    "-I${hndSrc}/bcmdrivers/opensource/include/bcm963xx"
    "-I${hndSrc}/shared/opensource/include/bcm963xx"
    "-I${hndSrc}/router/nvram"
    "-I${wlSrc}"
    "-I${wlShared}/bcmwifi/include"
  ];

  # Broadcom wireless components include paths (for wlioctl.h, ethernet.h)
  wlComponents = "${srcBase}/bcmdrivers/broadcom/net/wl/impl51/main/components";

  baseDefines = [
    "-DHND_ROUTER" "-DHND_ROUTER_AX" "-DLINUX26" "-DCONFIG_BCMWL5"
    "-DRTCONFIG_BCMWL6"  # Use bcmwifi_channels.h instead of missing bcmwifi.h
    "-DTYPEDEF_BOOL" "-DTYPEDEF_FLOAT_T"  # Prevent Broadcom bool/float_t redefinition (C23 keywords)
    "-DWL11AC_80P80" "-DWL11AC_160"
    "-D__EXPORTED_HEADERS__" "-DTEST1" "-DTRAFFIC_MGMT"
    "-DASUS_DDNS" "-DTRANSLATE_ON_FLY" "-DFLASH_EMULATOR" "-DLinux"
    "-DCHIP_4908" "-DCONFIG_BCM94908"
    "-DLINUX_KERNEL_VERSION=264451"
    "-DDEBUG_NOISY" "-DDEBUG_RCTEST"
  ];

  # Additional include paths for Broadcom wireless component headers
  baseCFlagsExtra = [
    "-I${wlComponents}/wlioctl/include"   # wlioctl.h
    "-I${wlComponents}/proto/include"     # ethernet.h (plain, no prefix)
    "-I${wlComponents}"                   # proto/ethernet.h (with prefix)
  ];

in stdenv.mkDerivation {
  pname = "libshared";
  version = "merlin-ng";

  src = asus-src;

  buildPhase = ''
    export CC="${toolPrefix}gcc"
    export AR="${toolPrefix}ar"
    export LD="${toolPrefix}ld"

    CFLAGS="${builtins.concatStringsSep " " (baseCFlags ++ baseCFlagsExtra ++ baseDefines)}"

    echo "=== Building libshared ==="

    SRC="$PWD/release/src-rt-5.02axhnd"
    SDIR="$SRC/router/shared"

    # Prepend build dir include path so generated headers (rtconfig.h) take
    # priority over nix-store copies found via -I${router}/shared.
    # Also add writable component stub paths for missing Broadcom headers.
    mkdir -p "$PWD/components"
    CFLAGS="-I$SDIR -I$SRC/router/nvram -I$PWD/components $CFLAGS"
    CFLAGS+=" -Wno-unused-result -Wno-error=format-security"
    CFLAGS+=" -include ctype.h -include $PWD/components/sighandler_compat.h"
    CFLAGS+=" -DOFFSET_MTD_FACTORY=0x40000 -DSPI_PARALLEL_NOR_FLASH_FACTORY_LENGTH=0x10000"
    CFLAGS+=" -DRT_VERSION=\\\"merlin-ng\\\" -DRT_SERIALNO=\\\"\\\" -DRT_RCNO=\\\"\\\""
    CFLAGS+=" -DRT_BUILD_NAME=\\\"RT-AX88U\\\" -DBUILD_NAME=\\\"RT-AX88U\\\""

    # Generate stub headers for Broadcom SDK headers not distributed in Merlin GPL
    cat > "$PWD/components/epivers.h" << 'STUB_EOF'
#ifndef _epivers_h_
#define _epivers_h_
#define EPI_VERSION_STR "1.0"
#define EPI_VERSION_MAJOR 1
#define EPI_VERSION_MINOR 0
#endif
STUB_EOF
    cat > "$PWD/components/utils.h" << 'STUB_EOF'
#ifndef _utils_h_
#define _utils_h_
/* Stub — original provides Broadcomm-specific utility functions */
#endif
STUB_EOF
    cat > "$PWD/components/bcmendian.h" << 'STUB_EOF'
#ifndef _bcmendian_h_
#define _bcmendian_h_
#include <endian.h>
#include <byteswap.h>
/* Broadcom byte swap functions (used by wl.c, etc.) */
#define bcmswap16(x) __bswap_16(x)
#define bcmswap32(x) __bswap_32(x)
#define bcmswap64(x) __bswap_64(x)
/* Convenience macros */
#define HTON16(x) htobe16(x)
#define HTON32(x) htobe32(x)
#define NTOH16(x) be16toh(x)
#define NTOH32(x) be32toh(x)
#endif
STUB_EOF
    cat > "$PWD/components/UdpLib.h" << 'STUB_EOF'
#ifndef _UdpLib_h_
#define _UdpLib_h_
/* Stub — Merlin UDP multicast utility */
#endif
STUB_EOF
    # httpd.h stub — only needed by vis_gui.c (which shouldn't be in libshared)
    cat > "$PWD/components/httpd.h" << 'STUB_EOF'
#ifndef _httpd_h_
#define _httpd_h_
/* Minimal stub for vis_gui.c */
typedef void *webs_t;
typedef void *wp;
#endif
STUB_EOF
    # autoconf.h stub — kernel-generated config header, not in Merlin GPL tree
    cat > "$PWD/components/autoconf.h" << 'STUB_EOF'
#ifndef _AUTOCONF_H
#define _AUTOCONF_H
/* Stub — normally generated by Linux kernel make config */
#endif
STUB_EOF
    # volume_id_internal.h — kernel volume management header, not in Merlin tree
    cat > "$PWD/components/volume_id_internal.h" << 'STUB_EOF'
#ifndef _VOLUME_ID_INTERNAL_H
#define _VOLUME_ID_INTERNAL_H
/* Stub */
#endif
STUB_EOF
    # version.h — auto-generated Merlin version header
    cat > "$PWD/components/version.h" << 'STUB_EOF'
#ifndef _VERSION_H_
#define _VERSION_H_
#define RT_BUILD_NAME "RT-AX88U"
#define BUILD_NAME "RT-AX88U"
#define FIRMWARE_VERSION "merlin-ng"
#endif
STUB_EOF
    # disk_io_tools.h — Merlin disk IO utility header
    cat > "$PWD/components/disk_io_tools.h" << 'STUB_EOF'
#ifndef _DISK_IO_TOOLS_H
#define _DISK_IO_TOOLS_H
/* Stub */
#endif
STUB_EOF
    # rtk_switch.h — Realtek switch driver header
    cat > "$PWD/components/rtk_switch.h" << 'STUB_EOF'
#ifndef _RTK_SWITCH_H
#define _RTK_SWITCH_H
/* Stub — Realtek switch not used on RT-AX88U (Broadcom) */
#endif
STUB_EOF
    # wlc_types.h — Broadcom wireless driver types
    cat > "$PWD/components/wlc_types.h" << 'STUB_EOF'
#ifndef _WLC_TYPES_H
#define _WLC_TYPES_H
/* Stub */
#endif
STUB_EOF
    # bled_defs.h — Bluetooth LED definitions
    cat > "$PWD/components/bled_defs.h" << 'STUB_EOF'
#ifndef _BLED_DEFS_H
#define _BLED_DEFS_H
/* Stub */
#endif
STUB_EOF
    # i2c-dev.h — Linux i2c device header (missing in build sandbox)
    cat > "$PWD/components/i2c-dev.h" << 'STUB_EOF'
#ifndef _I2C_DEV_H
#define _I2C_DEV_H
/* Stub */
#endif
STUB_EOF
    # usb_info.h — Merlin USB info header
    cat > "$PWD/components/usb_info.h" << 'STUB_EOF'
#ifndef _USB_INFO_H
#define _USB_INFO_H
/* Stub */
#endif
STUB_EOF
    # linux/compiler.h — kernel header, stub for flash_mtd.c
    mkdir -p "$PWD/components/linux"
    cat > "$PWD/components/linux/compiler.h" << 'STUB_EOF'
#ifndef _LINUX_COMPILER_H
#define _LINUX_COMPILER_H
/* Stub */
#endif
STUB_EOF
    # rtk_types.h — Realtek switch types, not used on Broadcom-based RT-AX88U
    cat > "$PWD/components/rtk_types.h" << 'STUB_EOF'
#ifndef _RTK_TYPES_H
#define _RTK_TYPES_H
/* Stub — Realtek switch types (Broadcom router) */
#endif
STUB_EOF
    # mtd-abi.h — kernel MTD userspace header (included as "mtd-abi.h")
    cat > "$PWD/components/mtd-abi.h" << 'STUB_EOF'
#ifndef __MTD_ABI_H__
#define __MTD_ABI_H__
/* Stub — kernel MTD ABI header, not in build sandbox */
#endif
STUB_EOF
    # proto/ethernet.h — wlif_utils.h includes "proto/ethernet.h" (quotes)
    # Redirect to the real ethernet.h via the proto/include include path.
    mkdir -p "$PWD/components/proto"
    cat > "$PWD/components/proto/ethernet.h" << 'STUB_EOF'
#include <ethernet.h>
STUB_EOF
    # sighandler_t compat — removed in modern glibc, replaced by sig_t
    cat > "$PWD/components/sighandler_compat.h" << 'STUB_EOF'
#ifndef _SIGHANDLER_COMPAT_H
#define _SIGHANDLER_COMPAT_H
#ifndef sighandler_t
#define sighandler_t sig_t
#endif
#endif
STUB_EOF
    # flash_mtd.h — provides OFFSET_MTD_FACTORY etc. for flash_mtd.c
    cat > "$PWD/components/flash_mtd.h" << 'STUB_EOF'
#ifndef _FLASH_MTD_H_
#define _FLASH_MTD_H_
#define OFFSET_MTD_FACTORY 0x40000
#define SPI_PARALLEL_NOR_FLASH_FACTORY_LENGTH 0x10000
#endif
STUB_EOF

    # Generate rtconfig.h from Merlin kernel config
    echo "--- Generating rtconfig.h ---"
    echo "/* Auto-generated */" > "$SDIR/rtconfig.h"
    while IFS='=' read -r key val; do
      case "X$key" in
        XCONFIG_*) echo "#define RTCONFIG_$(echo "$key" | sed 's/^CONFIG_//') $val" ;;
      esac
    done < "${kernelConfig}" >> "$SDIR/rtconfig.h"
    cat >> "$SDIR/rtconfig.h" << 'RTEOC'
#define RTCONFIG_HND_ROUTER_AX y
#define RTCONFIG_BCMARM y
#define RTCONFIG_SHP
#define BUILD_NAME "RT-AX88U"
RTEOC

    # Fix broken paren in shared.h (Broadcom typo)
    sed -i 's/__attribute__((unused) \*/__attribute__((unused)) */g' "$SDIR/shared.h"
    # Fix incompatible-pointer error in shutils.c:2708 (struct maclist* → char*)
    sed -i 's/char \*buf = maclist/char *buf = (char *) maclist/' "$SDIR/shutils.c"

    # Objects: compile sources, skip failures gracefully
    SOURCE_OBJS=""
    for f in "$SDIR"/*.c; do
      base=$(basename "$f" .c)
      # vis_gui.c depends on httpd.h (web server header) — not a shared lib dep
      if [ "$base" = "vis_gui" ]; then
        echo "  [skip] $base.c (httpd dependency, not shared)"
        continue
      fi
      # For AX/RT-AX88U, prefer _ax variant over base when both exist
      # (avoids duplicate symbol definitions at link time)
      case "$base" in
        wlif_utils)
          # wlif_utils_ax.o will be compiled separately; skip base variant
          echo "  [skip] $base.c (using _ax variant for AX platform)"
          continue
          ;;
      esac
      if [ -f "$SDIR/prebuild/RT-AX88U/$base.o" ]; then
        echo "  [prebuilt] $base.o"
        cp "$SDIR/prebuild/RT-AX88U/$base.o" "$SDIR/"
        SOURCE_OBJS="$SOURCE_OBJS $SDIR/$base.o"
      else
        echo "  [compile] $base.c"
        $CC $CFLAGS -c -o "$SDIR/$base.o" "$f" \
          && SOURCE_OBJS="$SOURCE_OBJS $SDIR/$base.o" \
          || echo "  [skip] $base.c"
      fi
    done

    # sysdeps/broadcom sources
    echo "=== sysdeps/broadcom ==="
    if [ -d "$SDIR/sysdeps/broadcom" ]; then
      for f in "$SDIR/sysdeps/broadcom"/*.c; do
        [ -f "$f" ] || continue
        base=$(basename "$f" .c)
        echo "  [compile] $f"
        $CC $CFLAGS -c -o "$SDIR/sysdeps_broadcom_$base.o" "$f" \
          && SOURCE_OBJS="$SOURCE_OBJS $SDIR/sysdeps_broadcom_$base.o" \
          || echo "  [skip] $f"
      done
    fi

    # Link shared library
    echo "=== Linking libshared.so ==="
    echo "Objects: $SOURCE_OBJS"
    $CC -shared -o "$SDIR/libshared.so" $SOURCE_OBJS -lpthread -lm
  '';

  installPhase = ''
    SRC="$PWD/release/src-rt-5.02axhnd"
    mkdir -p $out/lib $out/include
    cp "$SRC/router/shared/libshared.so" $out/lib/
    cp "$SRC/router/shared"/*.h $out/include/ 2>/dev/null || true
  '';

  meta = {
    description = "ASUSWRT-Merlin shared utility library for RT-AX88U";
    platforms = [ "aarch64-linux" ];
    license = lib.licenses.gpl2Only;
  };
}
