# Reads .rendered/runtime-config.json from the assistant repo.
# The file is generated by scripts/fetch_vault.sh and gitignored.
# If it doesn't exist yet (pre-bootstrap), returns stub values so nix eval
# doesn't fail — the user must run fetch_vault.sh before deploying.
{ assistant-repo }:
let
  configPath = assistant-repo + "/.rendered/runtime-config.json";
  cfg =
    if builtins.pathExists configPath
    then builtins.fromJSON (builtins.readFile configPath)
    else {
      domain = "REDACTED-DOMAIN";
      subdomains = [ ];
      backup = {
        s3 = {
          endpoint = "https://REDACTED-OBJECTSTORAGE";
          bucket = "REDACTED-BUCKET";
        };
      };
    };
in cfg
